### ISSUE TITLE
Espresso test in dev branch fails in espresso

### ISSUE THREAD

**Issue by JensWehner** [votca/csg#400]
regression_spce_ibi_espresso

**Comment by junghans** [comment]
https://github.com/votca/votca/pull/175

**Comment by junghans** [comment]
Get run and passed again in https://gitlab.com/votca/votca/-/jobs/278290703

**Comment by junghans** [comment]
Seems to happen on Rawhide only.

**Comment by junghans** [comment]
Looking at `inverse.log` on Rawhide it says:
```
Traceback (most recent call last):
  File "spce.py", line 74, in <module>
    write_force=True, write_species=False, write_mass=True, write_ordered=False)
  File "/usr/lib64/python3.7/site-packages/openmpi/espressomd/io/writer/h5md.py", line 83, in __init__
    "ScriptInterface::Writer::H5mdScript")
  File "script_interface.pyx", line 29, in espressomd.script_interface.PScriptInterface.__init__
ValueError: Class 'ScriptInterface::Writer::H5mdScript' not found.
```

Or something is wrong with the h5md backend in espresso.

@jkrajniak any idea?

**Comment by junghans** [comment]
Looking at https://kojipkgs.fedoraproject.org//packages/espresso/4.0.2/6.fc32/data/logs/x86_64/build.log:
```
- The following OPTIONAL packages have been found:
 * FFTW3
 * HDF5 (required version >= 1.8), parallel
 * PkgConfig
 * GSL
```
so Espresso got compiled with hdf5 enabled.

**Comment by junghans** [comment]
But:
```
-- Found HDF5: /usr/lib64/openmpi/lib/libhdf5.so;/usr/lib64/libsz.so;/usr/lib64/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so (found suitable version "1.10.5", minimum required is "1.8") found components:  C 
-- The Python module h5py was not found. (missing: PY_H5PY) 
```
so that might be it.

**Comment by junghans** [comment]
Ok I think the rpm missed a:
```
BuildRequires:       python%{python3_pkgversion}-h5py
```
will fix that in rawhide.

**Comment by junghans** [comment]
https://koji.fedoraproject.org/koji/taskinfo?taskID=37445736

**Comment by junghans** [comment]
Hmm, the new rawhide misses MDAnalysis, which Espresso needs.
