### ISSUE TITLE
Manpage conversion fails with rednotebook's version of txt2tags

### ISSUE THREAD

**Issue by junghans** [votca/csg#414]
```
[  0%] Building votca-csg manpage
cd /builds/votca/csg/votca/build/csg/share/man && /usr/bin/txt2tags -q -t man -i /builds/votca/csg/votca/csg/share/man/votca-csg.t2t -o /builds/votca/csg/votca/build/csg/share/man/votca-csg.man
make[2]: Leaving directory '/builds/votca/csg/votca/build'
/usr/bin/txt2tags:872: SyntaxWarning: invalid escape sequence \s
  'title1'               : '~A~\section*{\a}'     ,
/usr/bin/txt2tags:878: SyntaxWarning: invalid escape sequence \s
  'numtitle1'            : '\n~A~\section{\a}'      ,
/usr/bin/txt2tags:913: SyntaxWarning: invalid escape sequence \l
  'bar2'                 : '\\rule{\linewidth}{1mm}',
/usr/bin/txt2tags:1323: SyntaxWarning: invalid escape sequence \(
  'listItemOpen'          : '.IP \(bu 3\n',
/usr/bin/txt2tags:2743: SyntaxWarning: invalid escape sequence \.
  basename = re.sub('\.(txt|t2t)$','',infile)
/usr/bin/txt2tags:2934: SyntaxWarning: invalid escape sequence \s
  cfgregex  = re.compile("""
/usr/bin/txt2tags:2942: SyntaxWarning: invalid escape sequence \s
  prepostregex = re.compile("""
/usr/bin/txt2tags:2957: SyntaxWarning: invalid escape sequence \s
  guicolors = re.compile("^([^\s]+\s+){3}[^\s]+") # 4 tokens
/usr/bin/txt2tags:2982: SyntaxWarning: invalid escape sequence \s
  value = re.split('\s+', value)
/usr/bin/txt2tags:3457: SyntaxWarning: invalid escape sequence \|
  m = re.search('\a(\|+)$', cell)
/usr/bin/txt2tags:3564: SyntaxWarning: invalid escape sequence \|
  m = re.search(' (\|+) *$', line)
/usr/bin/txt2tags:3570: SyntaxWarning: invalid escape sequence \|
  line = re.sub(' (\|+)\| ', '\a\\1 | ', line)
/usr/bin/txt2tags:3576: SyntaxWarning: invalid escape sequence \|
  ret['cells'] = [re.sub('\a\|+$','',x) for x in ret['cells']]
/usr/bin/txt2tags:3876: SyntaxWarning: invalid escape sequence \s
  re.match('^\s*<center>.*</center>\s*$', lines[0]):
/usr/bin/txt2tags:4163: SyntaxWarning: invalid escape sequence \.
  elif flag == 'e': x = re.search('.(\.([^.]+))?$', info['name']).group(2) or ''
/usr/bin/txt2tags:4159: SyntaxWarning: invalid escape sequence \.
  elif flag == 'F': x = re.sub('\.[^.]*$','',info['name'])
/usr/bin/txt2tags:4390: SyntaxWarning: invalid escape sequence \.
  val = [re.sub('(?i)\.sty$','',x) for x in val]
/usr/bin/txt2tags:4544: SyntaxWarning: invalid escape sequence \#
  txt = re.sub('<','<\#60>',txt)
/usr/bin/txt2tags:4591: SyntaxWarning: invalid escape sequence \ 
  "Replace any Escape Char \ with a text mask (Input: str or list)"
/usr/bin/txt2tags:4597: SyntaxWarning: invalid escape sequence \ 
  "Undo the Escape char \ masking (Input: str or list)"
/usr/bin/txt2tags:4931: SyntaxWarning: invalid escape sequence \s
  if re.match('^\s+$', rest):
Sorry! Txt2tags aborted by an unknown error.
Please send the following Error Traceback to the author (verde@aurelio.net):

Traceback (most recent call last):
  File "/usr/bin/txt2tags", line 5997, in <module>
    exec_command_line()
  File "/usr/bin/txt2tags", line 5991, in exec_command_line
    convert_this_files(infiles_config)
  File "/usr/bin/txt2tags", line 4906, in convert_this_files
    finish_him(outlist, myconf)
  File "/usr/bin/txt2tags", line 4287, in finish_him
    Savefile(outfile, addLineBreaks(outlist))
  File "/usr/bin/txt2tags", line 2200, in Savefile
    doit(contents)
TypeError: a bytes-like object is required, not 'str'
```
even though the t2t file is pretty simple: https://github.com/votca/csg/blob/master/share/man/votca-csg.t2t

**Comment by junghans** [comment]
@jendrikseipp any ideas?

**Comment by junghans** [comment]
It seems that version https://github.com/nvdajp/txt2tags works for us.

**Comment by junghans** [comment]
@jendrikseipp works with python-3.7.4, but not 3.8.0b3, which is used on Rawhide.

**Comment by jendrikseipp** [comment]
Thanks for the heads-up, this is now fixed in the RedNotebook repo.

**Comment by junghans** [comment]
@jendrikseipp thanks for the quick fix. I will bump it in our container and see if it works!

**Comment by junghans** [comment]
I had to do some minor backslash tweak, but it seems good to go now.
